<a href="https://colab.research.google.com/github/22hash/AIMLLabs/blob/main/LinearAlgebraBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
import functools as ft
from operator import add, mul
import random

In [2]:
def get_random_vector(dimensions=2):
    """Generates two n dimensional vectors integer coordinates between 1 to 10"""
    vector1 = np.array([random.randint(1,10) for x in range(dimensions)])
    vector2 = np.array([random.randint(1,10) for x in range(dimensions)])
    return vector1, vector2 

In [3]:
dimensions = 2
a, b = get_random_vector(dimensions)

# dimensions = 2
# a, b = np.array([3,5]), np.array([8,2])
a, b

(array([5, 2]), array([ 2, 10]))

In [4]:
#Magnitude/Norm
norm_a = np.linalg.norm(a)
norm_b = np.linalg.norm(b)
norm_a, norm_b

(5.385164807134504, 10.198039027185569)

### Unit vector

$\bar{x}' = \dfrac{\bar{x}}{||\bar{x}||} = \dfrac{\bar{x}}{\sqrt{\bar{x}.\bar{x}}}$

In [5]:
def unit_vector(vector):
    return vector/np.linalg.norm(vector)

In [6]:
#Unit vectors
ua = unit_vector(a)
ub = unit_vector(b)
ub, ua

(array([0.19611614, 0.98058068]), array([0.92847669, 0.37139068]))

In [7]:
#Magnitude/Norm of unit vector
print(np.linalg.norm(ua))
print(np.linalg.norm(ub))

1.0
1.0


### Vector Addition
$ \bar{x} + \bar{y} = [x1 . . . xd] + [y1 . . . yd] = [x1 + y1 . . . xd + yd] $

In [8]:
#Addition of the two vectors
a + b

array([ 7, 12])

### Vector Subtraction
$ \bar{x} - \bar{y} = [x1 . . . xd] − [y1 . . . yd] = [x1 − y1 . . . xd − yd]$

In [9]:
#Subtraction of the two vectors
a - b

array([ 3, -8])

### Vector Scaling
$ \bar{x}' = a\bar{x} = [ax1 . . . a xd] $

In [10]:
#Scaling of the vector/ multiplication with a scalar
10*a

array([50, 20])

In [11]:
#Multiplication of the two vectors
a*b

array([10, 20])

### Dot Product
$ \bar{x} · \bar{y} = \displaystyle\sum\limits_{i=1}^d x_i y_i $

In [12]:
#Dot product
np.dot(a,b)

30

#### Dot product of a vector with itself is square of its magnitude
$||\bar{x}||^2 = \bar{x}·\bar{x} = \displaystyle\sum\limits_{i=1}^d x_i^2$

In [13]:
#Check if dot product of a vector with itself is square of its magnitude
assert (np.dot(a,a))**0.5 == norm_a
assert (np.dot(b,b))**0.5 == norm_b
print("ok")

ok


#### Dot product of two vectors is projection of one vector on another multiplied by the second vectors norm
$ \bar{x} · \bar{y} = ||\bar{x}||  ||\bar{y}||  \cos\theta $

In [14]:
def geometric_dot(x, y, theta):
    """Result of dot product of two vectors using the angle between the vectors"""
    norm_x = np.linalg.norm(x)
    norm_y = np.linalg.norm(y)
    return norm_x * norm_y * math.cos(math.radians(theta))

In [15]:
#Getting angle between the two vectors in degrees for two dimensional vector
if dimensions == 2:
    theta_a = math.degrees(math.acos(a[0]/norm_a))
    theta_b = math.degrees(math.acos(b[0]/norm_b))
    angle_between_ab = theta_a - theta_b
    print(angle_between_ab)

-56.888658039627984


In [16]:
#Check if cos(theta) = dot product of the unit vectors where theta is the angle between the vectors
if dimensions == 2:
    print(math.acos(np.dot(ua,ub)))
    print(math.radians(angle_between_ab))
    assert abs(round(math.radians(angle_between_ab),10)) == round(math.acos(np.dot(ua,ub)),10)
    print("ok")


0.9928943898326509
-0.9928943898326511
ok


In [17]:
#Checking if numpy's dot function result is same as our geometric dot function
if dimensions == 2:
    print(round(geometric_dot(a, b, angle_between_ab)))
    print(np.dot(a, b))
    assert round(geometric_dot(a, b, angle_between_ab)) == np.dot(a, b)
    print("ok")

30
30
ok


In [18]:
#Simulating numpy's dot function
def my_dot(vector1, vector2):
    return ft.reduce(add, map(mul, vector1, vector2))

In [19]:
#Check if simulation works
assert my_dot(a, b) == np.dot(a, b)
print("ok")

ok
